[package]
name = "render"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[dependencies]
shader_ast = {path="./shader_ast"}
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.7", features = ["serde", "v4"] }

[target.x86_64-apple-darwin.dependencies]
closefds = "*"
libc = "0.2"
time = "0.1.4"
metal = "0.14"
cocoa = "0.18"
core-graphics = "*"
objc-foundation = "0.1"
objc_id = "0.1"
objc = "0.2.3"

[target.x86_64-pc-windows-gnu.dependencies]
wio = "*"
time = "0.1.4"

[target.x86_64-pc-windows-gnu.dependencies.winapi]
version = "*"
features = ["dwmapi", "libloaderapi", "shellscalingapi", "winuser", "winbase", "d3d11", "d3d11sdklayers", "d3dcommon", "d3dcompiler", "dxgi1_2", "dxgiformat", "dxgitype", "winerror"]

[target.x86_64-pc-windows-msvc.dependencies]
wio = "*"
time = "0.1.4"

[target.x86_64-pc-windows-msvc.dependencies.winapi]
version = "*"
features = ["dwmapi","libloaderapi", "shellscalingapi", "winuser", "winbase", "d3d11", "d3d11sdklayers", "d3dcommon", "d3dcompiler", "dxgi1_2", "dxgiformat", "dxgitype", "winerror"]
